# Generated by Django 3.2.19 on 2023-06-24 21:24

import django.core.validators
from django.db import migrations, models
import memberzone.models


class Migration(migrations.Migration):

    dependencies = [
        ('memberzone', '0002_alter_bookingtimes_booking_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(default=memberzone.models.next_day, validators=[django.core.validators.MinValueValidator(memberzone.models.next_day)])),
            ],
        ),
        migrations.AlterField(
            model_name='bookingtimes',
            name='booking_date',
            field=models.DateField(default=memberzone.models.next_day, validators=[django.core.validators.MinValueValidator(memberzone.models.next_day)]),
        ),
        migrations.AlterField(
            model_name='bookingtimes',
            name='number_players',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
    ]
